In [1]:
import seaserpent as ss

In [225]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
# first read from info 
info = ss.Table('info', base='main')
infodf = info.to_frame()
infodf['root_id'] = infodf.root_id.astype(np.int64)
infodf.head()

supervoxel_id             root_id     pos_x  \
row_id                                                                    
IBmHKx4ERsizCJNgYd_5SA  80152954824646675  720575940621522189  138936.0   
Xf0lzmQaSo2e_Jz4vmhsHA  78112261444987077  720575940628857210  109306.0   
JcgRmmdaRtaY2Fq_tsTEXw  82475466912542440  720575940626838909  172029.0   
fz6y9HuPSPmZhSbLVfCs8A  82827998029690530  720575940645746286  177648.0   
Q48ynfJkQdanAYxTuK1peQ  83038623024880664  720575940626046919  180632.0   

                          pos_y   pos_z    soma_x   soma_y  soma_z  \
row_id                                                               
IBmHKx4ERsizCJNgYd_5SA  50352.0  2271.0  140648.0  49064.0  2262.0   
Xf0lzmQaSo2e_Jz4vmhsHA  50491.0  3960.0  104904.0  47464.0  5461.0   
JcgRmmdaRtaY2Fq_tsTEXw  55635.0  1592.0  177472.0  56936.0  1429.0   
fz6y9HuPSPmZhSbLVfCs8A  65848.0  3245.0  177648.0  65848.0  3245.0   
Q48ynfJkQdanAYxTuK1peQ  58664.0  1925.0  180632.0  58664.0  1925.0   

                        nucleus_id   side  ...        status  notes lrcid  \
row_id                                     ...                              
IBmHKx4ERsizCJNgYd_5SA   5717891.0   left  ...  not_a_neuron   None  None   
Xf0lzmQaSo2e_Jz4vmhsHA   2453924.0  right  ...      adequate   None  None   
JcgRmmdaRtaY2Fq_tsTEXw   7393349.0   left  ...      adequate   None  None   
fz6y9HuPSPmZhSbLVfCs8A   7416439.0   left  ...   merge_error   None  None   
Q48ynfJkQdanAYxTuK1peQ   7415038.0   left  ...          None   None  None   

                       root_duplicated proofread  root_last_modified  \
row_id                                                                 
IBmHKx4ERsizCJNgYd_5SA            True     False                 NaT   
Xf0lzmQaSo2e_Jz4vmhsHA           False      True 2022-04-26 22:12:00   
JcgRmmdaRtaY2Fq_tsTEXw           False      True 2022-09-30 20:19:00   
fz6y9HuPSPmZhSbLVfCs8A            True     False 2022-12-12 01:17:00   
Q48ynfJkQdanAYxTuK1peQ           False      True 2021-04-12 15:44:00   

                       last_user LM_match LM_match_source            root_526  
row_id                                                                         
IBmHKx4ERsizCJNgYd_5SA   scripts     None            None  720575940621522189  
Xf0lzmQaSo2e_Jz4vmhsHA   scripts     None            None  720575940628857210  
JcgRmmdaRtaY2Fq_tsTEXw   scripts     None            None  720575940626838909  
fz6y9HuPSPmZhSbLVfCs8A   scripts     None            None  720575940620666246  
Q48ynfJkQdanAYxTuK1peQ   scripts     None            None  720575940626046919  

[5 rows x 35 columns]

In [4]:
# also read all the connectivity from syn_proof_analysis
ff = pd.read_feather('/Users/yijieyin/Downloads/syn_proof_analysis_filtered_530.feather')
ff.head()

pre_pt_root_id     post_pt_root_id neuropil  syn_count
0  720575940617895883  720575940625455247    LAL_L          4
1  720575940618110513  720575940628422555      PRW          1
2  720575940621768180  720575940631845004    CRE_R         10
3  720575940619938145  720575940616262401   AVLP_L          4
4  720575940620405638  720575940629450622    CRE_R          3

In [5]:
# which neuropils are there? 
ff['neuropil'].unique()

array(['LAL_L', 'PRW', 'CRE_R', 'AVLP_L', 'SMP_R', 'CRE_L', 'AVLP_R',
       'AL_R', 'MB_ML_R', 'SIP_L', 'MB_VL_L', 'EB', 'MB_ML_L', 'SMP_L',
       'FLA_R', 'LAL_R', 'AL_L', 'AOTU_R', 'AOTU_L', 'MB_PED_L',
       'MB_VL_R', 'GNG', 'GA_L', 'FLA_L', 'SLP_L', 'PVLP_L', 'GA_R',
       'None', 'MB_PED_R', 'SIP_R', 'AMMC_L', 'SAD', 'AMMC_R', 'LO_R',
       'LH_R', 'LOP_L', 'LOP_R', 'PVLP_R', 'ME_L', 'IPS_R', 'LO_L',
       'IB_R', 'LH_L', 'ME_R', 'IPS_L', 'MB_CA_R', 'SCL_R', 'SLP_R',
       'SCL_L', 'ICL_R', 'PLP_R', 'EPA_R', 'FB', 'SPS_R', 'WED_R', 'IB_L',
       'ICL_L', 'CAN_R', 'SPS_L', 'PLP_L', 'VES_R', 'MB_CA_L', 'ATL_L',
       'ATL_R', 'VES_L', 'WED_L', 'PB', 'GOR_L', 'GOR_R', 'NO', 'CAN_L',
       'AME_L', 'EPA_L', 'BU_R', 'AME_R', 'BU_L'], dtype=object)

In [24]:
# connections in the neuropils we want 
npff = ff[(ff['neuropil'].isin(['AL_L','AL_R'])) & (ff['syn_count'] > 3)]
npff

pre_pt_root_id     post_pt_root_id neuropil  syn_count
8         720575940626202237  720575940624700140     AL_R          4
12        720575940634034839  720575940660217473     AL_R         38
21        720575940633372185  720575940618021755     AL_L         32
38        720575940626682682  720575940625431870     AL_L          4
39        720575940623289578  720575940632368992     AL_L         32
...                      ...                 ...      ...        ...
13723495  720575940622574532  720575940638025818     AL_L          5
13723583  720575940628335183  720575940623955637     AL_L          5
13723700  720575940654436769  720575940619061662     AL_L          5
13724680  720575940622977799  720575940622650879     AL_L          4
13726594  720575940627690246  720575940614548765     AL_R          4

[82493 rows x 4 columns]

In [25]:
# calculate total number of postsynapses per neuron for those in the neuropil of choice
npids = npff['pre_pt_root_id'].append(npff['post_pt_root_id']).unique()
npids = ff[ff['post_pt_root_id'].isin(npids)].groupby(['post_pt_root_id']).agg(totpostsyn = ('syn_count','sum'),).reset_index()
# add meta data 
npids = pd.merge(npids, infodf[['root_id','cell_type','cell_class','side']], 
                 left_on = 'post_pt_root_id', 
                 right_on = 'root_id')
npids

post_pt_root_id  totpostsyn             root_id  cell_type  \
0     720575940603231916         841  720575940603231916    DA1_lPN   
1     720575940603311020         252  720575940603311020   M_adPNm8   
2     720575940603356128         101  720575940603356128    ORN_DM2   
3     720575940603430112          48  720575940603430112   ORN_VM5d   
4     720575940603446374         148  720575940603446374  M_lvPNm47   
...                  ...         ...                 ...        ...   
3903  720575940659996033          28  720575940659996033    ORN_DA1   
3904  720575940660217473        4004  720575940660217473       None   
3905  720575940660217473        4004  720575940660217473       None   
3906  720575940660217729        3342  720575940660217729    lLN1_bc   
3907  720575940660217985        3167  720575940660217985    lLN2P_b   

     cell_class   side  
0          ALPN  right  
1          ALPN  right  
2     olfactory   left  
3     olfactory  right  
4          ALPN   left  
...         ...    ...  
3903  olfactory  right  
3904       ALLN  right  
3905       ALLN  right  
3906       ALLN   left  
3907       ALLN   left  

[3908 rows x 6 columns]

In [26]:
# what are the cell classes? 
npids.cell_class.unique()

array(['ALPN', 'olfactory', 'hygrosensory', 'ALLN', None, 'DN', 'AN',
       'MBON', 'visual_projection', 'ALIN', 'visual_centrifugal',
       'thermosensory', 'ALON', 'unknown_sensory', 'LHCENT', 'endocrine',
       'CSD', 'mAL'], dtype=object)

In [27]:
# group by cell_type or ids 
npids['newtype'] = [npids.loc[i, 'cell_type'] if npids.loc[i, 'cell_type'] != None else npids.loc[i, 'root_id'].astype(str) for i in range(npids.shape[0])]
nptypes = npids.groupby(['newtype']).agg(totpostsyntype = ('totpostsyn', 'sum'),).reset_index()
nptypes

newtype  totpostsyntype
0    720575940604008160              90
1    720575940604150560            1019
2    720575940604568521             129
3    720575940604662700             244
4    720575940605068390             251
..                  ...             ...
959               vLN24            2227
960               vLN25            5779
961               vLN26             556
962               vLN27            1023
963               vLN29            1708

[964 rows x 2 columns]

In [28]:
# add meta data from info, and total postsynapse number for each neuron 
# default is inner join: discard connections with cells not present in info 
# presynaptic id 
npff = pd.merge(npff, infodf[['root_id','cell_type','cell_class','side']], 
             left_on = 'pre_pt_root_id', 
             right_on = 'root_id')
# add total post synapse and meta info for postsynaptic id 
npff = pd.merge(npff, npids, on = 'post_pt_root_id', suffixes = ('_pre','_post'))
# total post synapse per postsynaptic newtype 
npff = pd.merge(npff, nptypes, on = 'newtype', how = 'left')
# add newtype info for presynaptic neuron 
npff['newtype_pre'] = [npff.loc[i, 'cell_type_pre'] if npff.loc[i, 'cell_type_pre'] != None else npff.loc[i, 'pre_pt_root_id'].astype(str) for i in range(npff.shape[0])]
# calculate neuron-neuron input proportion 
npff['inprop'] = npff.syn_count / npff.totpostsyn
npff

pre_pt_root_id     post_pt_root_id neuropil  syn_count  \
0      720575940626202237  720575940624700140     AL_R          4   
1      720575940634034839  720575940624700140     AL_R         16   
2      720575940613734893  720575940624700140     AL_R         37   
3      720575940614457086  720575940624700140     AL_R        532   
4      720575940621441494  720575940624700140     AL_R          6   
...                   ...                 ...      ...        ...   
96950  720575940610384281  720575940606407881     AL_L          4   
96951  720575940653877409  720575940642715040     AL_R          4   
96952  720575940615559892  720575940622602025     AL_L          4   
96953  720575940630608236  720575940612208346     AL_L          4   
96954  720575940631147335  720575940624886160     AL_L          5   

              root_id_pre cell_type_pre cell_class_pre side_pre  totpostsyn  \
0      720575940626202237       ORN_DM4      olfactory     left        8937   
1      720575940634034839       lLN1_bc           ALLN    right        8937   
2      720575940613734893          None           ALLN    right        8937   
3      720575940614457086       lLN2F_b           ALLN    right        8937   
4      720575940621441494          None           ALLN     left        8937   
...                   ...           ...            ...      ...         ...   
96950  720575940610384281          None           None     left         872   
96951  720575940653877409   Putative AN             AN    right         623   
96952  720575940615559892    DNp_EM_342             DN    right         423   
96953  720575940630608236          None           None     left         584   
96954  720575940631147335          None           None     left         244   

             root_id_post cell_type_post cell_class_post side_post  \
0      720575940624700140        lLN2T_c            ALLN     right   
1      720575940624700140        lLN2T_c            ALLN     right   
2      720575940624700140        lLN2T_c            ALLN     right   
3      720575940624700140        lLN2T_c            ALLN     right   
4      720575940624700140        lLN2T_c            ALLN     right   
...                   ...            ...             ...       ...   
96950  720575940606407881           None            None      left   
96951  720575940642715040           None            None     right   
96952  720575940622602025           None            None      left   
96953  720575940612208346           None            None      left   
96954  720575940624886160           None            None      left   

                  newtype  totpostsyntype         newtype_pre    inprop  
0                 lLN2T_c           32380             ORN_DM4  0.000448  
1                 lLN2T_c           32380             lLN1_bc  0.001790  
2                 lLN2T_c           32380  720575940613734893  0.004140  
3                 lLN2T_c           32380             lLN2F_b  0.059528  
4                 lLN2T_c           32380  720575940621441494  0.000671  
...                   ...             ...                 ...       ...  
96950  720575940606407881             872  720575940610384281  0.004587  
96951  720575940642715040             623         Putative AN  0.006421  
96952  720575940622602025             423          DNp_EM_342  0.009456  
96953  720575940612208346             584  720575940630608236  0.006849  
96954  720575940624886160             244  720575940631147335  0.020492  

[96955 rows x 17 columns]

In [119]:
# type-type input proportion 
ttnpff = npff.groupby(['newtype_pre','newtype','totpostsyntype','cell_class_pre','cell_class_post']).agg(typesyncount = ('syn_count', 'sum'),).reset_index()
ttnpff['inproptype'] = ttnpff['typesyncount'] / ttnpff['totpostsyntype']
ttnpff.sort_values(by = 'inproptype', ascending = False)

newtype_pre             newtype  totpostsyntype cell_class_pre  \
13854               ORN_V              l2LN23            1246      olfactory   
14516             ORN_VM6               v2LN5            3499      olfactory   
14616            TRN_VP1m  720575940622625279             681  thermosensory   
14636            TRN_VP1m  720575940636751326             653  thermosensory   
14459             ORN_VM6  720575940617295901            1103      olfactory   
...                   ...                 ...             ...            ...   
12720           M_l2PNm16             lLN1_bc          132333           ALPN   
3526   720575940621778646             lLN1_bc          132333           ALLN   
14448            ORN_VM5v             lLN1_bc          132333      olfactory   
14507             ORN_VM6             lLN1_bc          132333      olfactory   
6248   720575940629589292             lLN1_bc          132333           ALLN   

      cell_class_post  typesyncount  inproptype  
13854            ALLN           861    0.691011  
14516            ALLN          2311    0.660474  
14616            ALLN           440    0.646109  
14636            ALLN           404    0.618683  
14459            ALLN           679    0.615594  
...               ...           ...         ...  
12720            ALLN             4    0.000030  
3526             ALLN             4    0.000030  
14448            ALLN             4    0.000030  
14507            ALLN             4    0.000030  
6248             ALLN             4    0.000030  

[20833 rows x 7 columns]

In [35]:
# check some by writing ids to clipboard 
npids.loc[npids.cell_type == 'l2LN23', 'root_id'].to_clipboard(index=False,header=False)

# Matrix making and multiplication

In [159]:
typeclassall = pd.concat([ttnpff[['newtype_pre','cell_class_pre']].rename(columns={'newtype_pre': 'type', 'cell_class_pre': 'cell_class'}), 
                          ttnpff[['newtype','cell_class_post']].rename(columns={'newtype': 'type', 'cell_class_post': 'cell_class'})])
typeclassall.drop_duplicates(inplace=True, ignore_index=True)
typeclassall['idx'] = range(typeclassall.shape[0])
typeclassall

type cell_class  idx
0    720575940604008160       ALLN    0
1    720575940604568521       ALLN    1
2    720575940604662700       ALLN    2
3    720575940605078560       ALLN    3
4    720575940605101758       ALLN    4
..                  ...        ...  ...
602          DNg_EM_191         DN  602
603           M_vPNml69       ALPN  603
604  720575940634903403       ALPN  604
605          DNb_EM_117         DN  605
606          DNg_EM_222         DN  606

[607 rows x 3 columns]

In [148]:
# Create a numpy array with the maximum number of nodes
max_node = typeclassall.shape[0]
adj_matrix = np.zeros((max_node, max_node))

# Loop through the edges and add the weight to the appropriate cells in the adjacency matrix
for _, edge in ttnpff.iterrows():
    adj_matrix[typeclassall[typeclassall.type == edge['newtype']].idx, typeclassall[typeclassall.type == edge['newtype_pre']].idx] = edge['inproptype']

adj_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [149]:
adj_matrix.shape

(607, 607)

In [155]:
typeclassall.cell_class.unique()

array(['ALLN', 'visual_projection', 'olfactory', 'ALPN', 'ALON', 'ALIN',
       'CSD', 'DN', 'hygrosensory', 'LHCENT', 'MBON', 'AN',
       'thermosensory', 'unknown_sensory', 'visual_centrifugal', 'mAL'],
      dtype=object)

In [163]:
# now, make the starting matrix, which is identity for the sensory neurons only 
im = np.zeros((max_node, max_node))

for i in range(typeclassall.shape[0]):
    if typeclassall.loc[i, 'cell_class'] == 'olfactory':
        im[i,i] = 1

im

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [178]:
# now, matrix multiplication 
steps = 5 
data = []

data.append(adj_matrix@im)

for step in range(steps-2): 
    
    data.append(np.linalg.matrix_power(adj_matrix, step + 2) @ im)
data

[array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])]

In [179]:
data[2].shape

(607, 607)

In [189]:
# 2 hops away, the second neuron's connectivity expressed in terms of receptor neurons 
sum(data[2][1,:])

0.026411368040564685

# Q&A 

### how much of a PN's input is accounted for by ORNs how many hops away? 

In [184]:
typeclassall.head()

type cell_class  idx
0  720575940604008160       ALLN    0
1  720575940604568521       ALLN    1
2  720575940604662700       ALLN    2
3  720575940605078560       ALLN    3
4  720575940605101758       ALLN    4

In [226]:
# we want a dataframe with the following columns: 
# postsynaptic PN type; number of hops; percentage contributed 
# so the sum of each row for the PN rows 
pn = []
perc = []
npns = typeclassall[typeclassall.cell_class == 'ALPN'].idx.size

for step in range(steps-1): 
    for row in typeclassall[typeclassall.cell_class == 'ALPN'].idx: 
        pn.append(typeclassall.type[row])
        perc.append(sum(data[step][row,:]))

pnhops = pd.DataFrame({'pn': pn, 'perc': perc, 'step': sorted(list(range(steps-1)) * npns)})
pnhops

pn      perc  step
0    720575940630057728  0.000000     0
1    720575940630134839  0.000000     0
2               DA1_lPN  0.263891     0
3               DA1_vPN  0.219107     0
4               DA2_lPN  0.206616     0
..                  ...       ...   ...
623            DL2d_vPN  0.060192     3
624             VM2_vPN  0.034059     3
625             DM3_vPN  0.006790     3
626           M_vPNml69  0.022970     3
627  720575940634903403  0.027031     3

[628 rows x 3 columns]

In [ ]:
fig = plt.figure()
ax = fig.add_axes([0,0,1,1])
ax.bar(X + 0.00, data[0], color = 'b', width = 0.25)
ax.bar(X + 0.25, data[1], color = 'g', width = 0.25)
ax.bar(X + 0.50, data[2], color = 'r', width = 0.25)

In [228]:
np.arange(4)

array([0, 1, 2, 3])